version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nargiza
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    ports:
      - "27010:27017"
    volumes:
      - ./mongo_data:/data/db
